version: "3.9"
services:
  flask:
    build: ./App
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"